name: Semgrep Security Scan
on:
  pull_request: {}
  push:
    branches: [main]
  schedule:
    - cron: '0 2 * * 0'  # Weekly scan

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  semgrep:
    name: Security Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
    - name: Checkout code
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - name: Setup Python
      uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
      with:
        python-version: '3.11'
    - name: Install Semgrep
      run: python3 -m pip install semgrep
    - name: Run Semgrep scan
      run: semgrep --config auto --sarif --output semgrep.sarif || true
    - name: Upload results to GitHub
      uses: github/codeql-action/upload-sarif@e2b3eafc8d227b0241d48be5f425d47c2d750a13 # v3.26.10
      if: always()
      with:
        sarif_file: semgrep.sarif
